[package]
name = "gattify-lab"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "gattify_lab_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
tauri-plugin-gattify = { path = "../../../crates/tauri-plugin-gattify" }

[dev-dependencies]
serde_json = "1"
tauri = { version = "2.11.5", features = ["test"] }

[workspace]
