[[permission]]
identifier = "allow-get-state"
description = "Allows reading adapter state."
commands.allow = ["get_state"]

[[permission]]
identifier = "deny-get-state"
description = "Denies reading adapter state."
commands.deny = ["get_state"]

